### ISSUE TITLE
Installing on Debian

### ISSUE THREAD

**Issue by dlockley** [UCLA-Plasma-Simulation-Group/QuickPIC-OpenSource#11]
when I run make, QUICKPIC cannot find the following files:

/usr/bin/ld: cannot find -libhdf5
/usr/bin/ld: cannot find -libhdf5_hl
/usr/bin/ld: cannot find -libhdf5_fortran

This results in a completion error. 

We can see the above files on the workstation and have already update make.GF_OPENMPI with the location of the files but this does not appear to have any effect.

Any advice would be much appreciated.

**Comment by caozigao** [comment]
Did you install the hdf5 libraries? If not, you have to do that for your workstation. Make sure you enable the parrallel option and fortran option when you run the configure script for hdf5.

**Comment by dlockley** [comment]
Yes, I have installed all the hdf5 library packages via package manager. 
We haven't yet run the configure script - where would find this? How do we run it and select the above options? Thanks.

**Comment by caozigao** [comment]
If you install the hdf5 from the source, you have to run the configure script first and then run make to build the library. There is a readme file included in the hdf5 source introducing how to set those options.

Since you said you already installed hdf5, I suggest you check where you installed it. The libraries may not stay in your "/usr/bin/ld"

**Comment by dlockley** [comment]
We installed hdf5 using the package manager rather than directly from the source. We have located all the related files which appear to be all linked to each other. Is there any way of checking that the files are linked correctly?   

"/usr/bin/ld" appears to be a file containing a link, is this correct? Your above note seems to imply it might be an actual directory?

Would you generally recommend that we install hdf5 from source rather than how we did it using the package manager? If we try installing from source does this mean we need to first remove the already installed files to avoid getting file duplicates?

Many thanks.

**Comment by caozigao** [comment]
I was wrong about "/usr/bin/ld". I suggest you build the hdf5 from the source and make sure you enable the parallel and fortran options. I don't know about the system you are using, so I cannot tell whether you need to remove the old files.
